using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HotProperty_PropertyAPI.Models
{
    public class PropertyNumber
    {
        //primary key but user to create, not generated by database.
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int PropertyNo { get; set; }
        public string SpecialDetails { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}
